version: "3"
services:
  food-pos-database:
    image: "postgres"
    env_file:
      - food_pos_database.env
    ports:
      - "5432:5432"
    volumes:
      - ./food-pos-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    ports:
      - "9090:80"
    volumes:
      - ./pgadmindata:/var/lib/pgadmin
    links:
      - "food-pos-database:pgsql-server"
